# For more information: https://laravel.com/docs/sail
version: '3'
services:
    pgsql:
        image: 'postgres:14'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
            - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
            retries: 3
            timeout: 5s
        networks:
            - sail
    chaters_backend:
        container_name: chaters_backend
        # hostname: main
        depends_on:
            - pgsql
        build:
            context: .
            dockerfile: dockerfile
        restart: unless-stopped
        ports:
            - "9000:9000" # Main App php-fpm
            - "6001:6001" # Websocket server
            - "9001:9001" # Main App
        volumes:
            - .:/var/www
            - /var/www/node_modules # empty node_modules folder, npm cannot create folder in container build,reason unknown
            - /var/www/vendor # empty vendor folder, composer create folder in container build,reason unknown
        command: sh  "./bin/init.sh"
        networks:
            - sail
    nginx: 
        image: nginx:alpine
        container_name: nginx_laravel
        restart: unless-stopped
        ports: 
            - "8000:8000"
        volumes:
            - './:/var/www'
            - './nginx:/etc/nginx/conf.d/'
        depends_on:
            -  chaters_backend
        networks:
            - sail
networks:
    sail:
        driver: bridge
            
#    laravel.test:
#        build:
#            context: ./vendor/laravel/sail/runtimes/8.1
#            dockerfile: Dockerfile
#            args:
#                WWWGROUP: '${WWWGROUP}'
#        image: sail-8.1/app
#        extra_hosts:
#            - 'host.docker.internal:host-gateway'
#        ports:
#            - '${APP_PORT:-80}:80'
#            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
#        environment:
#            WWWUSER: '${WWWUSER}'
#            LARAVEL_SAIL: 1
#            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
#            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
#        volumes:
#            - '.:/var/www/html'
#        networks:
#            - sail
#        depends_on:
#            - pgsql
#    
volumes:
    sail-pgsql:
        driver: local
